version: '3.9'

services:
  user-frontend:
    build: ./user-frontend
    volumes:
      - ./user-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - user-backend
    networks:
      - app-network

  admin-frontend:
    build: ./admin-frontend
    volumes:
      - ./admin-frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - admin-backend
    networks:
      - app-network

  user-backend:
    build: ./user-backend
    container_name: user-backend
    volumes:
      - ./user-backend:/app
      - /app/node_modules
    ports:
      - "4001:4000"
    environment:
      - MONGO_URI=mongodb://user-mongo:27017/userdb
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT=http://localstack:4566
    depends_on:
      - user-mongo
      - localstack
    command: npx nodemon index.js
    networks:
      - app-network

  admin-backend:
    build: ./admin-backend
    container_name: admin-backend
    volumes:
      - ./admin-backend:/app
      - /app/node_modules
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://admin-mongo:27017/admindb
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT=http://localstack:4566
    depends_on:
      - admin-mongo
      - localstack
    command: npx nodemon index.js
    networks:
      - app-network

  user-mongo:
    image: mongo
    container_name: user-mongo
    ports:
      - "27017:27017"
    volumes:
      - user-mongo-data:/data/db
    networks:
      - app-network

  admin-mongo:
    image: mongo
    container_name: admin-mongo
    ports:
      - "27018:27017"
    volumes:
      - admin-mongo-data:/data/db
    networks:
      - app-network

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/data/localstack
    volumes:
      - ./.localstack:/data/localstack
    networks:
      - app-network

volumes:
  user-mongo-data:
  admin-mongo-data:

networks:
  app-network:
    driver: bridge
